#!/bin/sh /etc/rc.common

START=99

boot() {
	case "$(board_name)" in
	edgecore,eap104)
		avail=$(fw_printenv -n upgrade_available)
		[ "${avail}" -eq 1 ] || fw_setenv upgrade_available 1
		fw_setenv bootcount 0
		;;
	hfcl,ion4xi_w)
		fw_setenv boot_count 0
		;;		
	esac
}
